// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"elm/internal/handler"
	"elm/internal/middleware"
	"elm/internal/repository"
	"elm/internal/server"
	"elm/internal/service"
	"elm/pkg/helper/sid"
	"elm/pkg/log"
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func newApp(viperViper *viper.Viper, logger *log.Logger) (*gin.Engine, func(), error) {
	jwt := middleware.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	sidSid := sid.NewSid()
	serviceService := service.NewService(logger, sidSid, jwt)
	db := repository.NewDB(viperViper)
	repositoryRepository := repository.NewRepository(db, logger)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	homeRepository := repository.NewHomeRepository(repositoryRepository)
	homeService := service.NewHomeService(serviceService, homeRepository)
	homeHandler := handler.NewHomeHandler(handlerHandler, homeService)
	articleRepository := repository.NewArticleRepository(repositoryRepository)
	articleService := service.NewArticleService(serviceService, articleRepository)
	articleHandler := handler.NewArticleHandler(handlerHandler, articleService)
	engine := server.NewServerHTTP(logger, jwt, userHandler, homeHandler, articleHandler)
	return engine, func() {
	}, nil
}

// wire.go:

var ServerSet = wire.NewSet(server.NewServerHTTP)

var SidSet = wire.NewSet(sid.NewSid)

var JwtSet = wire.NewSet(middleware.NewJwt)

var HandlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewHomeHandler, handler.NewArticleHandler)

var ServiceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewHomeService, service.NewArticleService)

var RepositorySet = wire.NewSet(repository.NewDB, repository.NewRedis, repository.NewRepository, repository.NewUserRepository, repository.NewHomeRepository, repository.NewArticleRepository)
